### ISSUE TITLE
grunt compile fails when run twice in a row

### ISSUE THREAD

**Issue by justinsb** [ngbp/ngbp#101]
I was experiencing some odd failures with grunt compile.  I've produced a simple repro / test case: install as per the "Quick Start" instructions in README.md, then run "grunt compile", then run "grunt compile" again.

On my setup, that immediately produces an error "Parser error in ng-boilerplate.css" when running the "recess:compile" task.

Running grunt compile, grunt watch, grunt compile does work.

**Comment by joshdmiller** [comment]
Yeah, this is a byproduct of the way the build works. But I don't think there's any reason to run `compile` twice in a row. If any files change, they won't get picked up without running `build` _before_ running another `compile`, which prevents this error from occurring. `watch` just operates off the build tasks, so that's why that sequence also works.

Do you have a need to run `compile` twice that I haven't thought of? If so, we'll certainly fix this; otherwise, it may not be worth it - though I don't object to PRs!

**Comment by justinsb** [comment]
Thanks for the explanation!

I think the docs led me to believe that I should run "grunt compile" if I wanted to get the final product.  I now realize I should use "grunt build compile" or just plain "grunt".

Thinking in terms of makefiles, the compile task should depend on build.  I changed the gruntfile to do that, but that then means build gets called twice by "grunt", as grunt doesn't seem to do intelligent execution, so that's not really a great option.

I was using "grunt compile" as a 'run everything' verification step, when I was upgrading some of the dependencies to newer versions.  I should have just run "grunt".

**Comment by joshdmiller** [comment]
The `compile` task will work if _either_ the `build` or the `watch` step was the last to run. So you can just run `compile` to get the final product, assuming you've been actively developing. The correct task to run to build from start to finish is always just the default task, which runs both `build` and `compile`; otherwise, these tasks can be run independently.

I'll go ahead and close this issue, but if there's an area of the docs you feel should be more clear then let me know - or feel free to submit a PR. :-)
