### ISSUE TITLE
Bootstrap 3

### ISSUE THREAD

**Issue by BerndWessels** [ngbp/ngbp#108]
Move to bootstrap 3.

I had compatibility issues between angular-bootstrap and bootstrap 3 - so I removed angular-bootstrap and used the native bootstrap 3 implementation.

Cheers
Bernd

**Comment by joshdmiller** [comment]
Yeah, we're currently working on updating angular-bootstrap to support Bootstrap 3.0. We're most of the way there; you can check our progress at angular-ui/bootstrap#742.

**Comment by BerndWessels** [comment]
Great, I'm looking forward to it.

**Comment by garthk** [comment]
Looks like #742 is as done as it's going to get. What do we need to do at this end?

**Comment by roychoo** [comment]
Hey josh,

i have submitted a pull request #137 for this. 
Do let me know your thoughts on this.

i didn't include specific bootstrap less files, instead just include the main bootstrap.less

-Roy

**Comment by amergin** [comment]
Any updates on this one?

**Comment by lanoxx** [comment]
I guess this can also be closed after issue #137 was closed today?

**Comment by BerndWessels** [comment]
Yes, looks great.

Big thanks to Josh and all contributors.

Looking forward to the exciting new 2.0 ;)

**Comment by joshdmiller** [comment]
Yes indeed, @lanoxx! Not sure how I missed this one.

@BerndWessels - definitely thanks to the contributors; I didn't do too much this time around. But, I'm working on a teaser video for the next version so we can get some alpha testers. Should be within the next week as I just pushed 90% of the code to a new repo (ngbp/warlock). I called it "Warlock" because "ngbp" makes me want to take a nap.
