### ISSUE TITLE
Where is promised directory structure?

### ISSUE THREAD

**Issue by e-oz** [ngbp/ngbp#111]
From readme:  
`A directory structure that is cogent, meaningful to new team members, and supporting of the above points.`

And where is that structure? All what we have for application is "src" folder almost without structure inside.

**Comment by ElliotPsyIT** [comment]
@jamm I would encourage you to take a closer look at that directory structure.  If you do, you might see more of its value - as others have - http://blog.artlogic.com/2013/05/02/ive-been-doing-it-wrong-part-1-of-3/ .

**Comment by e-oz** [comment]
@fielstem I don't see here ANY structure. It's almost empty folder. 
`Application-specific code lives under app/`
Where are these files?
All code (all controllers, routes, config) in just one app.js? It's ridiculous, it's not structure.

**Comment by offner** [comment]
@jamm You are rushing to conclusions without fully understanding this project. I would also encourage you to take some time to familiarize yourself with the project before you make yourself look too much more obnoxious than you already have.

**Comment by ElliotPsyIT** [comment]
@jamm Are you sure you're looking under /src directory?  The /src directory has a READme.md describing the structure which I show below.  And if you care to read more about the wisdom in it, consider reviewing the blog post I previously suggested.  Personally, I think it will be well worth your time.

``` src/
  |- app/
  |  |- about/
  |  |- home/
  |  |- app.js
  |  |- app.spec.js
  |- assets/
  |  |- fonts/
  |- common/
  |  |- plusOne/
  |  |- titleService/
  |- less/
  |  |- main.less
  |  |- font-awesome.less
  |  |- variables.less
  |- index.html
```

**Comment by joshdmiller** [comment]
Whoa - a lot has happened in my absence. That's okay - I encourage lively debate. :-)

@jamm I understand your confusion. The documentation covers most of this, but I'll try to sum it up. 

First, ngBoilerplate is a _boilerplate_ and not a complete application; the only way to demo a detailed directory structure would be to include a bunch of additional and irrelevant code (which you don't like, per #112). 

Second, ngBoilerplate isn't a directory structure _itself_, but rather a set of tools to make use of a cogent directory structure. The included code makes use of this directory structure, but cannot highlight all its features (per the first point). That is, the structure is defined and supported but not _thoroughly_ demonstrated.

Third - and this is the important part - here are the directory-related points that ngBoilerplate supports and encourages:
- Isolated modules
- Nested modules
- Nested routing, matching module structure
- Organization by feature rather than by layer
- Adjacent tests
- Separating re-usable "common" code from app-specific code

These features lead to these benefits:
- Drag-and-drop component reuse
- Cleaner test-driven development
- Shorter ramp-up for new developers
- Much, much more.

You may also find the thoughts I shared to the Yeoman project helpful: yeoman/generator-angular#109. They ultimately adopted a similar approach as well.

I hope this helps clarify things. I'll leave this issue open for now; please feel free to post a followup here.

**Comment by e-oz** [comment]
@fielstem in initial comment I should mention "app" folder, sorry.

@joshdmiller so you are presenting your project without examples? To see how will it work I have to spend some time just to initialize your project and then decide? Then what for all this documentation?
All what I see at this moment in `app` folder is strange home.js where controller mixed with config and routing. Does it mean that structure, generated by ng-boilerplate will push all controllers of "home" into one file, with all routes and directives also? Because I don't see folder `directives`.

**Comment by joshdmiller** [comment]
@jamm As documented in the READMEs, _everything_ is pushed into a single file; all JavaScript sources (except tests) and all templates/partials (through the `$templateCache`) are put into a _single_ resulting JavaScript file. All CSS and LESS files are similarly compiled into a _single_ file. So after building, you have `index.html`, `app-name-version.js`, `app-name-version.css`, and an `assets/` folder which ngBoilerplate does not touch.

There are no "examples". ngBoilerplate is just a toolchain. It's up to you to use it as you see fit; I've provided some documentation to make things easier. Keep in mind that the READMEs say how to _use_ the toolchain. You say there is nothing in the `app/` folder, but that's not entirely true: there are two examples. The `home` module's [README](https://github.com/joshdmiller/ng-boilerplate/blob/v0.3.0-release/src/app/home/README.md) should provide some illumination on how to structure modules. But, again, you'll need to read _all_ of the README files to get an understanding of the directory structure.

Also, check out that Yeoman link I gave; there's _a lot_ of the background thinking there. For example, you say you don't find a `directives` folder; that's because ngBoilerplate says that having such a folder is emphatically **wrong**. Here's from that Yeoman link: "Instead of bundling code by the layer to which it belongs (controllers, services, filters, directives, etc.), I would like to see code bundled by the feature to which it belongs." That document lists some examples with further explanation. Please read it; I think you'll find it helpful.

I'm sorry you're having trouble here and I'd like to help. If there's something missing with the docs I'm eager to fix it, but I'm having difficulty locating from where your confusion is arising. 

But also keep in mind that I provide all of this in my free time and without compensation. :-)

**Comment by e-oz** [comment]
@joshdmiller I'm talking not about files in build folder. If "directives" folder is wrong for directives (already surprisingly), then where should be directives of "home"? In "common"? If yes - where exactly, in which folder? If not - where? In home.js? I've read all your short documentation (90% is about working with Grunt, not about architecture of application).

**Comment by joshdmiller** [comment]
I'm not talking about the `build` folder either. I was talking about `src/app`.

The answer to your directive question isn't straightforward. There's no way to answer "where do I put a directive" because the answer will depend on what the directive does and how it is used. If it is a generic, reusable directive then it can go in `src/common`. See the [`plusOne`](https://github.com/joshdmiller/ng-boilerplate/tree/v0.3.0-release/src/common/plusOne) directive that comes with ngBoilerplate for an example of exactly that.

But if it isn't a generic directive but rather is something app-specific, then it belongs bundled with that _feature_. There is an example in the Yeoman link; it doesn't sound like you've read it yet. See the subsection called "(b) Multi-Component Features" in the "Organize by Feature" section. Features are placed in the `app/` folder unless the feature as a whole is also re-usable, in which case it arguably goes in `common`.

But all of these details are not questions of _how_ ngBoilerplate works but questions as to best practices when developing applications that use it. You complain about my documentation being mostly about Grunt, but that is the way it should be. ngBoilerplate is a _toolchain_. You can completely ignore my advice about proper structure and place components wherever you want in `src/` or `common/` and ngBoilerplate is smart enough to handle it correctly. ngBoilerplate exists because at the time I created it, no other toolchains supported the more "correct" structure.

Okay. I'm going to go ahead and close this now. GitHub issues aren't really meant for extended conversations of this nature. I'd like to keep the GitHub issues mostly geared toward remediable problems and potential features. Perhaps I should create a mailing list where these discussions would be more productive.

**Comment by e-oz** [comment]
@joshdmiller in `common` I see directive and service.
Main aim of good folders structure is to be predictable (when I can predict where can I find needed file). When `common` is just a folder for all things - it's not organized folder and it's bad.
And if that link (https://github.com/yeoman/generator-angular/issues/109) and whole conversation is required to understand aims and ideas of your project - mention it somehow in documentation.

**Comment by joshdmiller** [comment]
I created a mailing list if you still have questions. https://groups.google.com/forum/#!forum/ng-boilerplate

**Comment by stela5** [comment]
@jamm, you may want to check out https://github.com/cgross/generator-cg-angular
