### ISSUE TITLE
Dirty index.html

### ISSUE THREAD

**Issue by e-oz** [ngbp/ngbp#112]
At this moment after cloning this project user should remove all the dirt from index.html if he wants to use it as template. There is tones of unnecessary things.
Is it supposed to be used as template ("seed")?

**Comment by colthreepv** [comment]
it's made so in order to provide something already functional and not a completely empty boilerplate, i think.

less than 5 minutes to tear it down anyway and replace the content with your own, i think it's an handy thing for people that never used AngularJS (as i were the first time i came to this project)

**Comment by e-oz** [comment]
I don't think it's "less than 5 minutes" and I thought this project is aimed to save my time. It was just opinion, good luck in evolving. Bye.

**Comment by e-oz** [comment]
And only as advice - consider to add "examples" folder in repository, rather than bloating "seed" with examples by default.

**Comment by colthreepv** [comment]
ahah, i also told my opinion, as the "useless" part of this boilerplate came useful to me at start since i knew very few to zero of Angular, anyway... reopen it and wait for @joshdmiller opinion, i was just passing by :walking:

**Comment by joshdmiller** [comment]
@jamm - You have a valid point, but I'm not sure how to address it perfectly. The boilerplate needs to run out of the box, but it should do so without a lot of stuff inside it. With `home` and `about` in their own modules, this shouldn't be a problem. What "dirt" do you think we should remove from `index.html`?

**Comment by e-oz** [comment]
@joshdmiller when "dirt" is quoted, it looks like you think things like `<meta name="twitter:creator" content="@joshdmiller">` and `<!-- it's stupid to have to load it here, but this is for the +1 button -->` should exist in each web app, generated by ngBoilerplate.
I know it sounds rude, but be little more serious when trying to show "standard" for developers. Even if this code is supposed to be replaced - it's not how template should be built (in my opinion). For example, `<meta name="twitter:creator" content="@<%= creator_twitter_name %">` could be better replacement. Because user shouldn't think "oh, what else I forgot to replace", but should have ability to replace strings in configuration file line by line.

**Comment by joshdmiller** [comment]
I put "dirt" in quotes so as to indicate that I was using your word but didn't know to what precisely you were referring. It's a proper usage in English grammar, so let's not get too touchy. :-)

Second, of what the heck value is a starter if one doesn't replace the templates? Of course the end user is going to change the templates because their site isn't going to look like mine. The templates contain the navigation; they contain social media links; they contain the footer. It's a template like any other - **of course** the user is expected to change it.

Just to clarify intent: ngBoilerplate is **not** meant to be an empty template. If it was, it also wouldn't include Bootstrap, Font Awesome, UI Bootstrap, angular-placeholders, or any other optional components - it would just be a Grunt configuration. But that's not my intent.

I offer this in my free time and without compensation in the hopes that others find it useful. Use it, don't use - but it is what it is.

Okay, all that said - if you have some specific ideas of how to _reduce_ (but not eliminate) some of the manual work in `index.html`, I'd love a pull request.

**Comment by e-oz** [comment]
@joshdmiller it's wrong policy "it's my free time so don't complain". I'm spending my time to improve your project without compensation too.
`It's a template like any other` - it's not a template, it's an example file. There is a HUGE difference.

Sorry for taking your free time, hope my time wasn't thrown on the wind also and you'll find something useful.

**Comment by joshdmiller** [comment]
I also never said not to complain; I merely implied that you should keep your tone in check, as others here have done. You may not realize it, but your messages come across very rude. 

I also said I would welcome a PR.
