### ISSUE TITLE
Why not use grunt-bower-task?

### ISSUE THREAD

**Issue by cemo** [ngbp/ngbp#138]
As a developer from Java world, the tools we are using are all-in-one styles tools such as Maven or Gradle. Maven is providing cleaning, installing, deploying, realising as well. Many conventions are created by Maven. 

Grunt is providing something very similar to Maven with Bower, NPM. But in order to install dependencies one needs to run `bower install`. I can not understand why is not `grunt-bower-task` replacing `bower`? Is this intentional or `grunt-bower-task` is not ready to replace `bower`? I would be really very glad if someone explain this.

Also I am ready to contribute for `grunt-bower-task` if you interested in.

**Comment by joshdmiller** [comment]
That's a good question. But `grunt-bower-task` _isn't_ a Bower replacement at all; instead, it runs Bower, collects files, and then manipulates the output to follow an arbitrary structure. ngBoilerplate has its own way of handling the files from Bower, so that wouldn't really add anything to the process here.

But NPM/Grunt and Bower are not redundant. If you're working on a Node project, NPM and Grunt are very much like Maven. But ngBoilerplate isn't for Node projects. It uses NPM and Grunt to build a project that doesn't run on node at all - it runs in a web browser. Node packages don't mean anything in the realm of Browsers, so we need a package manager that does; that's Bower. NPM manages dependencies needed by our build system (similar to a crazy-complex Makefile), but Bower manages our _application_ dependencies, which makes it in the case of ngBoilerplate closer to Maven than NPM is.

That said, if running two tools bothers you it wouldn't be very difficult to create a Grunt task that just executes Bower for you (possibly even without the binary). I don't have the time to do that right now, but I'd happily take a look at a pull request.

**Comment by cemo** [comment]
@joshdmiller thanks for the detailed explanation. Actually I have not enough knowledge on _javascript configuration world_ and was curious of what you think.  As far as I know `grunt-bower-task` can be configured to be running without manipulating too. 

When I am looking a java project, I can only see one configuration file, `pom.xml` but this is not valid for javascript world, and worse It is becoming terrible. There is maybe at least 10 configuration file which is clearly pointing a problem. Why do I have to learn so many tools at the same time? Why don't we provide an abstraction for them?  

I admit that the current javascript world is better than 2 years ago. `GruntJS` has done a good job in this area but still needs big steps. It seems that the tools in javascript world still are at the beginning of their life and evolving very rapidly. Inevitably these tools will must converge at one point. 

I am closing this request for currently. I will re-open this issue and submit a pull request when the community and these tools mature enough. 

Thanks.
