### ISSUE TITLE
I am wondering of status for this project?

### ISSUE THREAD

**Issue by svycka** [ngbp/ngbp#140]
I see 22 open pull requests, two milestones past due date by more than 2 months no commits for 3 months so I am wondering whats going on.

ping @joshdmiller

**Comment by daverodz** [comment]
I think Josh is extremely busy and they have a working version but yea,
maybe have other people that can work on applying changes or somehting?

Good call Vytautas.

-David.

**Comment by joshdmiller** [comment]
Hey @svycka - This is a very fair question. @daverodz is right; the last few months have been extraordinarily busy. Rest assured, this project is not dead.

This afternoon I merged 16 pull requests and closed a handful of issues. Right now, I'm working to knock out a few more. Later today I'll be releasing v0.3.1 and next week I will be pushing v0.4.0, which will have a few major new features.

I also plan to extend an invitation to see who is interested in becoming committers so that everything is not entirely dependent on me. There are hundreds of users and this is too much for a dude with a day job. :-)

I'm going to close this as answered, but feel free to followup.
