### ISSUE TITLE
How to disable obfuscating

### ISSUE THREAD

**Issue by svycka** [ngbp/ngbp#143]
somehow after obfuscation some places in my app stops working without any errors. I tryed remove uglify in grunt file and then everything works but also I lost minification functionality that's because uglify does minification and obfuscation. As I don't have time to investigate why it doesn't work. I would like to disable obfuuscation temporary. Is it possible?

**Comment by joshdmiller** [comment]
I'm not sure how you're distinguishing minification from obfuscation. If you mean "mangling" (which is done for minification, not obfuscation), then you can turn that off with `mangle: false`, but then the only benefit of minification is reducing whitespace. Otherwise, can you be more specific about what you want UglifyJS not to do?

For the record, here are all options available: https://github.com/gruntjs/grunt-contrib-uglify.

**Comment by svycka** [comment]
yep, this is what I needed. thanks helped.

As I am not sure that my code doesn't work or something from vendor folder, maybe there is a way to disable only for vendor/ folder? or src/ to see with one fails? it's hard to debug when no error occurs.

**Comment by svycka** [comment]
I finally find out my issue https://github.com/btford/ngmin/issues/35 and thats why mangling failed
