### ISSUE TITLE
How to have an xhr loaded HTML Snipet ?

### ISSUE THREAD

**Issue by jeremieca** [ngbp/ngbp#151]
Hello,

With my project, all my template javascript in my apps are transformed to Js file. But I would like to use Xhr calls to load my templates.

The problem is :
When the build is done, my apps' HTML template aren't copy from src to an build directory.
For example, src/app/panel/views/app.tpl.html is not copied to build/panel/views/app.tpl.html. So Xhr does not work.

Thanks !
Jérémie C.

**Comment by joshdmiller** [comment]
Hey @jeremieca - It's the policy of ngBoilerplate to not use XHR calls for templates but to rather support an initial payload. It's been my experience that this leads to a better user experience _in most cases_.

But ngBoilerplate is very flexible indeed. Simply remove the `html2js` task from the build task, remove the `templates-app` and `templates-common` dependencies from `app.js`, and then add your template glob to one of the copy tasks (based on where you want to put them in the build); a logical place would be to add them to the `build/assets` directory, e.g. something like this:

``` js
copy: {
  build_app_tpls: {
    files: [
      { 
        src: [ '<%= app_files.html %>' ],
        dest: '<%= build_dir %>/assets/',
        cwd: '.',
        expand: true
      }
    ]   
  },
  // ...
}
```

And then add it to the `build` task in place of `html2js`. Also note that you could forego adding a copy task if you keep your templates in `src/assets/` as they will already be picked up by the build, but then you lose organization by feature.

I'm going to close this issue because it's not officially supported (though it may be in a subsequent version), but you're more than welcome to ask a followup so let us know if you encounter issues implementing the above.
