### ISSUE TITLE
Module-specific styles should be automatically imported into build

### ISSUE THREAD

**Issue by cristobalchao** [ngbp/ngbp#158]
Hey there,

 It would be great if the developer doesn't have to deal with this.

Best,

Cristobal

**Comment by PaulL1** [comment]
I presume this means concatenating the less files from each module together into main.less?  To do this, we'd have to make some assumptions about where in main.less we want them.  If we assume that they all go at the end of main.less, then it is probably doable.

I see this tool: https://npmjs.org/package/grunt-less-imports, which seems to do some extra trickiness around giving any less compiler errors on a per-file basis rather for the concatenated whole.  That could be nice, but I'm not sure whether Josh would want that added into the ng-boilerplate.

Otherwise, I've looked through the LESS documentation, and through bits of the Grunt documentation, and I don't see any immediately obvious way to add these imports automatically.

**Comment by SamHowie** [comment]
I have made a first pass at this. Please see following pull request: https://github.com/ngbp/ng-boilerplate/pull/179

As mentioned by @PaulL1 I did make the assumption that all imports were to be appended to the end of the main.less file.

**Comment by michaelbromley** [comment]
Just want to comment that I implemented a solution using [grunt-less-imports](https://github.com/MarcDiethelm/grunt-less-imports) as suggested by @PaulL1 and it works very well.

I configured it in the Gruntfile like this:

``` JavaScript
less_imports: {
            build: {
                options: {
                },
                src: ['src/less/main.less', 'src/**/*.less', '!src/less/variables.less', '!src/less/master.less'],
                dest: 'src/less/master.less'
            }
        },
```

and added it as a step before the `less` task (I'm using grunt-contrib-less rather than recess) in the `build` and `watch` tasks. 

Then I modified `build.config.js` to set the source of the `less` task to be the single `master.less` file that was generated by `less_imports:build`

``` JavaScript
less: 'src/less/master.less'
```

**Comment by esco** [comment]
:+1:

**Comment by joshdmiller** [comment]
My thought is to address this as part of a basic directory structure change in #356.
