### ISSUE TITLE
NPM Install Warnings/Errors

### ISSUE THREAD

**Issue by k3n** [ngbp/ngbp#163]
Hi! I'm on Win7 x64, and I cloned the repo and then ran `npm install`, and there were lots of warns/errors in the output. I wouldn't think this is expected, but I don't see it mentioned anywhere.

I do realize that most, if not all, of these are from 3rd parties. However, my concern is around the impact on ng-boilerplate -- considering these warnings, is my ng-boilerplate "ok", or will I need to do additional work to ensure that everything is in its place?

```
npm WARN package.json jshint@1.1.0 No repository field.
```

```
npm WARN package.json dateformat@1.0.2-1.2.3 No repository field.
```

```
npm WARN package.json peakle@0.0.1 No repository field.
```

```
npm WARN package.json vows@0.7.0 No repository field.
```

```
npm WARN package.json faye-websocket@0.4.4 No repository field.
npm WARN package.json faye-websocket@0.4.4 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
```

```
npm WARN package.json eyes@0.1.8 No repository field.
```

```
npm http GET https://registry.npmjs.org/glob

> coffeelint@0.5.7 install C:\dev\node_modules\grunt-coffeelint\node_modules\coffeelint
> [ -e lib/commandline.js ] || npm run compile

'[' is not recognized as an internal or external command,
operable program or batch file.
npm http 304 https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/wordwrap

> coffeelint@0.5.7 compile C:\dev\node_modules\grunt-coffeelint\node_modules\coffeelint
> coffee -c -o lib src
```

```
npm WARN package.json policyfile@0.0.4 No repository field.
npm WARN package.json policyfile@0.0.4 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
```

```
npm WARN package.json cookie-signature@1.0.1 No repository field.
```

```
npm WARN package.json bytes@0.2.0 No repository field.
```

```
npm WARN package.json pause@0.0.1 No repository field.
npm WARN package.json methods@0.0.1 No repository field.
npm WARN package.json methods@0.0.1 No readme data.
npm WARN package.json uid2@0.0.2 No repository field.
npm WARN package.json uid2@0.0.2 No readme data.
```

```
npm WARN package.json range-parser@0.0.4 No repository field.
```

```
npm http 200 https://registry.npmjs.org/nan/-/nan-0.3.2.tgz

> ws@0.4.31 install C:\dev\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\dev\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws>node "C:\Program Files\nodejs\node_modules
\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
```

**Comment by joshdmiller** [comment]
These warnings are a consequence of the way NPM works. When you install a package through NPM, it downloads and builds it along with all the other components it requires (and all the components _those_ components require, ad infinitum).

NPM requires certain fields to be present in a library's `package.json` file in order to install; others, it simply encourages through warnings, like the readme and repository. Some of these encouraged fields are frequently left out by developers.

Putting it all together, when you install ngBoilerplate, some of its dependencies don't have all the encouraged but optional fields (though they have all the required ones) so NPM throws up a little warning to let you know. This has no effect on ngBoilerplate. If you're not familiar with NPM, that can be confusing to see, but unless you see an actual error everything is working as it should.

So, to conclude, your boilerplate is "ok". :-)

**Comment by k3n** [comment]
Ok, thanks. I've used NPM several times, but usually it's just a few deps and everything seems to go off without a hitch. Thanks for the explanation!
