### ISSUE TITLE
This is really cool - routing question

### ISSUE THREAD

**Issue by conoremclaughlin** [ngbp/ngbp#17]
Hi Josh,

So I noticed for each part of the site you're setting up the routes yourself.  The about page is an example of this:

https://github.com/joshdmiller/ng-boilerplate/blob/master/src/app/about/about.js

Do you worry about url collisions for more complex applications?  And more importantly, do you have a vision for how to handle deep-link navigation, Ie. if I had a root url:

`https://mysite.com/help`

and wanted to set up separate pages for each help page:
- `https://mysite.com/help/intro`
- `https://mysite.com/help/logging-in`

etc. I've been unable to find anything conclusive online, but can I only specify a full path to the routeHandler?  Like I can't just watch for route changes on everything after my module's root url (similar to how express does it with applications, for example).

Thank ya kindly and keep up the awesome work!
Conor

**Comment by conoremclaughlin** [comment]
or hash urls for that matter - #step1, #step2, etc.

**Comment by joshdmiller** [comment]
Hey @conoremclaughlin!

Terribly sorry it took me a few days to respond to this one. I'm normally much more responsive, but it's been one of those weeks. :)

I don't worry too much about collisions. You're right that they're possible (just like they're possible if they're defined in the same file) and the likelihood increases with the complexity of the app; I'm sure at some point, our URLs will start to collide. That said, if everything's properly nested, I see it as less likely. That is, if our routes _roughly_ follow our folder nesting, the colliding routes should be in the same module anyway and we should therefore be more easily aware of this.

True deep linking is trickier (I'm considering including [`uiRouter`](https://github.com/angular-ui/ui-router) instead of the default `$routeProvider`), but your case is actually very simple:

```
about/
|-- help/
|-- |-- help.js
|-- |-- intro.tpl.html
|-- |-- loggingIn.tpl.html
```

Because of the simple nature of it, you can define the routes and controllers inside `help.js` and include the templates right there. If the content of these pages was more complicated, then we could have subfolders within `help/` to store more routes and controllers, etc.

Does that answer the question or did I completely miss the point?

**Comment by conoremclaughlin** [comment]
Hi @joshdmiller,

Thanks so much for the thorough response!  I'm having one of those weeks as well so my apologies for the delay.

I checked out uiRouter and it actually looks like it formalizes and betters some of the solutions I've come up with to address various weaknesses in angular.  I just started working at a new company, so I'm basically restructuring their entire angular application to follow the module format.  I realize now part of my problem is legacy.

We have a mobile and desktop application, and I'd like to do two things:
1. Break various components into separate modules that could be dragged and dropped.
2. Deal with base urls as they've adopted a layer approach and all their templates sit in a folder - including the index.html that is not at the root.

Issue 2 will be addressed with time as I finish refactoring and introducing a build process to their workflow (this a problem right now because of product cycles and the time involved training other members of the team), but just in the immediate future I thought it'd be lovely to have something similar to require.js' path resolution (or as a first step to the build process) before actually integrating grunt.

It looks like angular doesn't have this capability by default, though.  Anyway, looks like you've added even more improvements.  I'll probably bounce some angular ideas off you later as I get more involved in it (if you're up to sharing the wisdom, of course, haha).

Thanks for your time and help!  I'll close this for now.
