### ISSUE TITLE
ui-utils/ui.route/$uiRoute vs ui-router/ui.router/$state for active nav decoration

### ISSUE THREAD

**Issue by tony-kerz** [ngbp/ngbp#197]
the `ui-router` sample shows how to use `$state` to decorate active navs here in [module.js](https://github.com/angular-ui/ui-router/blob/master/sample/module.js#L7)  and here in [index.html](https://github.com/angular-ui/ui-router/blob/master/sample/index.html#L41)

`ngbp` shows how to use `$uiRoute` to accomplish a similar end here in [index.html](https://github.com/ngbp/ng-boilerplate/blob/v0.3.1-release/src/index.html#L42)

being a noob, i found this a little confusing. 

my little journey down this path started with me:
- attempting to use `ui-router` 0.2.0
- the routing not working
- temporarily confusing the `ui.route` module with the `ui.router` module
- trying to understand where `ui.route` was coming from
- spotting the dependency on `ui-utils`
- trying to find detailed documentation on `ui-utils`
- finally coming to some understanding of `ui-route`/`$uiRoute` via examples

so i was wondering if an app is made a decision to use `ui-router`, then perhaps it should use `$state` for active nav (and potentially avoid the additional dependency on the somewhat sparsely documented `ui-utils` bundle (assuming it isn't being used for something else))?

at the same time, i understand that the code sample portion of `ngbp` may fall into the grey area of what you are trying to advocate, so interested in your take on this topic (especially since i see you are a contributor to the `angular-ui` project ;)

**Comment by joshdmiller** [comment]
Sorry it took me so long to get to this. :-(

The pattern I generally use is the `$state` one, but the `$uiRoute` directive provides a nice, clean syntax. For an example as simply as this, its inclusion is a spot silly, I agree. And you're also right that it's in the gray area - I just wanted to include some bower plugins.

However, v0.4 of ngbp is a _massive_ shaekup and the example will be quite different - and there will probably be no `ui-router` (purely for convenience and file size). Since 0.4 will make this issue sort of irrelevant, I'll go ahead and close it, but feel free to continue the discussion.
