### ISSUE TITLE
Grunt build does not concat js files

### ISSUE THREAD

**Issue by artworkad** [ngbp/ngbp#199]
I use the default setup and issue

```
grunt build --force
```

and get following output

> Running "clean:0" (clean) task
> Cleaning "build"...OK
> 
> Running "clean:1" (clean) task
> 
> Running "html2js:app" (html2js) task
> Successfully converted 1 html templates to js.
> 
> Running "html2js:common" (html2js) task
> Successfully converted 1 html templates to js.
> 
> Running "jshint:src" (jshint) task
> Linting src/app/app.js...ERROR
> [L216:C21] W116: Expected '{' and instead saw 'scope'.
>                     scope.sortdir = scope.sortdir === 'asc' ? 'desc' : 'asc';
> [L231:C13] W116: Expected '{' and instead saw 'length'.
>             length = 10;
> [L234:C13] W116: Expected '{' and instead saw 'end'.
>             end = "...";
> 
> Warning: Task "jshint:src" failed. Used --force, continuing.
> 
> Running "jshint:test" (jshint) task
> 3 files lint free.
> 
> Running "jshint:gruntfile" (jshint) task
> 1 file lint free.
> 
> Running "jshint:globals" (jshint) task
> 0 files lint free.
> 
> Running "coffeelint:src" (coffeelint) task
> Warning: must provide pattern Used --force, continuing.
> 
> Running "coffeelint:test" (coffeelint) task
> Warning: must provide pattern Used --force, continuing.
> 
> Running "coffee:source" (coffee) task
> Warning: must provide pattern Used --force, continuing.
> 
> Running "recess:build" (recess) task
> File "build/assets/ng-boilerplate-0.3.1.css" created.
> 
> Running "concat:build_css" (concat) task
> File "build/assets/ng-boilerplate-0.3.1.css" created.
> 
> Running "copy:build_app_assets" (copy) task
> Created 1 directories, copied 1 files
> 
> Running "copy:build_vendor_assets" (copy) task
> Copied 5 files
> 
> Running "copy:build_appjs" (copy) task
> Copied 3 files
> 
> Running "copy:build_vendorjs" (copy) task
> Copied 10 files
> 
> Running "index:build" (index) task
> 
> Running "karmaconfig:unit" (karmaconfig) task
> 
> Running "karma:continuous" (karma) task

The js files in the vendor folder are not merged to a single file. The files are just copied to the build folder. Any ideas why?

**Comment by joshdmiller** [comment]
Because that's what's supposed to happen. :-)

There are two tasks: `build` and `compile`. The former is only for  development, during which you would not want concatenated files because that makes errors harder to locate and slow down the iterative build cycle. The `compile` task gets the app ready for production, including concatenating all the files. The readme goes into more detail about this distinction.

The `index.html` file in  development iterates through all files and includes them automatically, whereas in  production there is only the single file.

Hope this helps!

**Comment by artworkad** [comment]
:+1: hehe thank you I missed that :)
