### ISSUE TITLE
Uglify only working with mangle:false

### ISSUE THREAD

**Issue by artworkad** [ngbp/ngbp#200]
My build project works fine. However when I compile it angular seems to stop working. Only when I set

```
mangle: false
```

to the uglify task it works again. However variable names are still exposed in the js code.

On page init I redirect to the zone.list state

```
angular.module('ngBoilerplate.zone', [
    'ui.router'
])

.config(function config($stateProvider) {

    $stateProvider
        .state('zone', {
            abstact: true,
            url: '/zone',
            template: '<ui-view/>'
        })
        .state('zone.list', {
            url: '/list',
            controller: 'ZoneListCtrl',
            templateUrl: 'zone/zone.list.tpl.html',
            data: {
                pageTitle: 'Zone'
            },
            //load zones
            resolve: {
                zones: function (ZoneService) {
                    return ZoneService.list();
                }
            }
        });
})
```

The compiled project neither loads the view nor the list of zones. My controllers are all chained

```
.controller('ZoneListCtrl', function ZoneListController($scope, zones)     {
    $scope.zones = zones;
})

.controller...
```

There are no errors in console. Any ideas whats wrong? I have read the requirements of ngmin and my code seems to fit them. However I am not sure if all angular bower components do.

**Comment by PaulL1** [comment]
I have this same issue, however I get errors in the console about b provider not being present.  The error originates in the Angular code somewhere I think.  I have tried including only the minified versions of the angular code, on the logic it perhaps wouldn't get minified again, but I still get the error.

I ultimately decided it was easier to just leave mangle turned off, I'm not sure it saves much anyway.

**Comment by igorhart** [comment]
Had the same issue as you, guys. The problem is that ng-min doesn't take
care of all params before they get mangled.
There are few cases when this happens: e.g. angular.module('',
[]).config($serviceThatWillBeScrewedByMangle)

I have tried to use different uglify's option called "except" to list all
the services, that I don't wish to get mangled, but there are too many of
them (most needed for ui-router) and it's not very futureproof, after all.

For me, mangle reduces final .js file's size by approx. 131 KB.
Imho, that's a lot. Hopefully, ng-min will get updated soon..

Cheers!
23 lis 2013 22:48 "PaulL1" notifications@github.com napisa³(a):

**Comment by joshdmiller** [comment]
I have not encountered this issue. Can someone provide either a reproduceable scenario or, preferably, an upstream issue report?

**Comment by SailingYYC** [comment]
I should have responded sooner as I spend several hours myself in the past reconciling this issue.

Ultimately the issue at hand is that the mangling breaks Angular's dependency injection.  So Angular has the $inject Annotation and Inline Annotation mechanisms for expressing a controller/directive's dependencies.  If you are to uglify your code, this is ALL Angular supports.

ngbp wants to keep our lives easy and uses ng-min, but it's limited in the scenarios it can automatically convert from pure function syntax to inline annotation.  If you define your function outside of these known scenarios, they will not survive uglification.

Having too many layers of abstraction, passing controllers around as anonymous functions, etc. ensures they will not survive uglification.

Inside of the controller that is throwing the error, this is the one that should be rewritten either in either $inject or inline syntax.

That will fix your problem, at least without waiting for ng-min to be updated.

**Comment by SailingYYC** [comment]
@ArtworkAD in your little snippet, you don't include `ZoneService` in your module definition, also possibly try the following:

``` js
.config(function config($stateProvider) {

    $stateProvider
        .state('zone', {
            abstact: true,
            url: '/zone',
            template: '<ui-view/>'
        })
        .state('zone.list', {
            url: '/list',
            controller: 'ZoneListCtrl',
            templateUrl: 'zone/zone.list.tpl.html',
            data: {
                pageTitle: 'Zone'
            },
            //load zones
            resolve: {
                zones: [ 'ZoneService', function (ZoneService) {
                    return ZoneService.list();
                } ]
            }
        });
})
```

**Comment by joshdmiller** [comment]
I'm with you guys, but what I need is either a reproducible scenario or an issue report on ng-min so that I can try to fix it. As I said, I do not encounter this issue. 

I am not in favor of disabling mangling - the file size differences are just too big.

**Comment by PaulL1** [comment]
I just tried it on my tutorial application - and that uglifies fine.  I'd hoped to get an easily reproducible scenario there.  However, I know my larger application doesn't uglify, so I need to work out what's different and then give a scenario.  I'll look at that today.

**Comment by artworkad** [comment]
Minified js: 80kb (14 ms load), mangled js: 66kb (19 ms load). However more important than the load time for me is that the code logic is harder to be exposed in the mangled version.

---

I've setup a simple test , git clone https://github.com/ArtworkAD/ng-boilerplate-uglify-test and php -S localhost:3000 and go to localhost:3000/bin/index.html. @joshdmiller 

It basically uses ui-router resolve a list of active issues on ng-boilerplate before displaying the view (click on show issues). The build verison works fine. The compiled version does not. I get no error message.

**Comment by joshdmiller** [comment]
@ArtworkAD Your code won't build for me. It will fail with Bootstrap 3, so I changed that; then you were missing `angular-mocks` from your Bower config, so I added that. And finally I get another build error:

```
Firefox 25.0.0 (Linux) home section should have a dummy test FAILED
        minErr/<@/store/dev/repos/tmp/ng-boilerplate-uglify-test/vendor/angular/angular.js:78
        loadModules/<@/store/dev/repos/tmp/ng-boilerplate-uglify-test/vendor/angular/angular.js:3573
        forEach@/store/dev/repos/tmp/ng-boilerplate-uglify-test/vendor/angular/angular.js:300
        loadModules@/store/dev/repos/tmp/ng-boilerplate-uglify-test/vendor/angular/angular.js:3538
        createInjector@/store/dev/repos/tmp/ng-boilerplate-uglify-test/vendor/angular/angular.js:3478
        workFn@/store/dev/repos/tmp/ng-boilerplate-uglify-test/vendor/angular-mocks/angular-mocks.js:2099
```

At this point, I give up. :-)

What I really need is a minimal reproducible scenario. That is, I want to see a small block of code that works unminified, and then I want to see what it looks like passed through `ng-min`, and finally what it looks like minified. That will tell us where the problem is. If the problem is mangling, then it's an `ng-min` problem and will have to be fixed upstream and we'll need to file a bug report to the team.

> However more important than the load time for me is that the code logic is harder to be exposed in the mangled version.

As a complete (and irrelevant aside) I hear this a lot from developers, but it doesn't really make any sense to me. From a security perspective, the logic is irrelevant as the sever should be verifying everything independently anyway. If not, we have a serious security problem.

From a copyright perspective, what needs such protection? In excess of 99% of apps, it's the idea of the app that is worth money - not the code. There is almost never some ingenious client-side algorithm that provides product differentiation in the marketplace. The user is already in your app and so knows what it does and how it's done. 

Besides, the network traffic is completely exposed. So if they want to copy or hack, they have everything they need anyway.

We have a tendency as developers to be paranoid and ultra-secretive and to think that we came up with some brilliant new solution; in reality, that's almost never the case. If someone wants to copy us, they don't need our unmangled code.

Anyway, irrelevant - but I usually have trouble keeping my mouth shut. :-)

**Comment by PaulL1** [comment]
@joshdmiller, I agree with you in theory on mangling for security.  

Having said that, I have heard stories of people's entire applications being copied, and if most of your application is in the Angular, it's plausible someone could copy all your code (usually with some minor modifications).  I believe this generally happens in places where copyright isn't overly respected, so whilst in theory copyright protects you, in practice it can be expensive or impossible to go down that route.  I've never had it happen to me in practice, but I think uglification erects an additional barrier.  It means that either, if you want to make minor modifications, you now need to invest serious effort in reverse engineering the code, or they need to just duplicate your code entirely (so they lose the ability to make even trivial changes, and any copyright argument would get easier as it's blatantly an exact copy).  I'm not convinced that this is really a solid argument, but it is at least a rational argument for wanting it.

Anyway, that's neither here nor there, I think the code size is a compelling enough reason.

Pull #202 has my minimal test case, it's driven by an http interceptor.  I suspect that means the interceptor needs to be written in a different format, and I don't have time before work this morning to look at how/why, but I suspect it's not overly hard.  And I also suspect that the problem isn't systemic - I managed to add every angular library / vendor library I'm using without getting any uglification errors, the first one only happened when I started adding my own application code.  Likely that @ArtworkAD has a different problem, perhaps with a similar cause, but again triggered by his application code.

UPDATE: I think the cause is pretty much exactly as @SailingYYC has mentioned, I have a function that has dependencies, and it isn't part of a chained controller or factory definition, so ngMin will miss it.

**Comment by PaulL1** [comment]
Snuck home at lunchtime.  This does solve the problem for me in my sample and my main app.

Mangling is the difference for me between 423K and 522K.  Not critical, but useful.

**Comment by joshdmiller** [comment]
I am not in favor of disabling mangling and the issue here is with ngmin rather than with ngbp. You can either disable mangling in your own apps or code in such a way as to make mangling irrelevant, but a fix across all projects that increases file sizes to prevent a rare and (otherwise preventable) issue that occurs with an upstream project doesn't seem like a good solution to me.

As such, I'm going to go ahead and close this issue.
