### ISSUE TITLE
Turn off karma

### ISSUE THREAD

**Issue by cole1911** [ngbp/ngbp#204]
It is not an issue, rather a question.
Is it possible to turn of karma tests ? Of course, I need karma during development but when I want to place project on server to let people watch the results I don't need karma there.

**Comment by joshdmiller** [comment]
I'm not entirely sure what you're asking; when you deploy the compiled project (from `bin/`), there is no build process at all and this no Karma. Can you elaborate on your use case?

**Comment by cole1911** [comment]
I'm using jenkins to build the project. When I use grunt watch  the build stops on:

[32mINFO [karma]: [39mKarma v0.10.6 server started at http://localhost:9018/

And I have to abort building.

**Comment by joshdmiller** [comment]
If you're doing CI, you should definitely be running Karma during the build. This project uses Travis and the [setup](https://github.com/ngbp/ng-boilerplate/blob/v0.3.1-release/.travis.yml) is relatively straightforward - it should be [similar](http://karma-runner.github.io/0.8/plus/Jenkins-CI.html) for Jenkins.

**Comment by cole1911** [comment]
Of course, but this build is for end users.

**Comment by PaulL1** [comment]
You would normally run a compile if going to end users, not a watch, as you'd want the bin rather than the build.  Although I guess either work.

The hang that you're getting looks suspiciously like what I get if I set the browsers list to empty in my karma unit config - that means that karma waits for a browser to connect before running any tests.  If that were the case, it could be because your CI server is headless, and perhaps you should be installing PhantomJS.  

A quick diagnostic to prove that would be to connect a browser (maybe from another machine) to port 9018 on the specified machine, and see if that makes the grunt watch run.

If that's not the problem, then it still looks suspiciously like your Karma is waiting for a browser to connect, so there might be something else going wrong with your browser setup/Karma setup on that machine.

**Comment by cole1911** [comment]
grunt build works the same way in my case.

I run this on debian, there is no any browsers.

I build this on server where is jenkins and then deploy to nginx on another server.

**Comment by PaulL1** [comment]
It would be good practice still to run the tests before sending to the users, in most cases you'd achieve that by installing PhantomJS on that server, which is a headless browser, so it can run on a server with no UI.  You'd then put PhantomJS into the Karma browser setup.

If you really don't want to run Karma, you can achieve that by modifying Gruntfile.js.  A couple of options for you:

Firstly, if you want to keep running grunt watch.  If so, then modify the following line to match:

```
grunt.registerTask( 'watch', [ 'build', 'delta' ] );
```

You'll also probably need to look through the sections of the task marked "delta" and delete the various references to karma:unit:run.  As an example, line 460.  You'd probably find it easier to modify the file by running grunt build instead of grunt watch, then you'd only need to modify line 566.

Alternatively, go to using grunt compile.  Which will give you more "production like" code for your users, run a bit faster, and in general make sure that what you're testing with your users is actually what you're pushing to production.  If you do that, then you do the same thing, but you need your CI server to run grunt build then grunt compile, and you need to change the build task to not run karma:unit:

```
grunt.registerTask( 'build', [
    'clean', 'html2js', 'jshint', 'coffeelint', 'coffee', 'recess:build',
    'concat:build_css', 'copy:build_app_assets', 'copy:build_vendor_assets',
    'copy:build_appjs', 'copy:build_vendorjs', 'index:build', 'karmaconfig' 
  ]);
```

You can also get the same effect by just running grunt with no command - it runs build then compile.  But you'll have to call it each time your CI server needs a new build - it won't watch a directory.
