### ISSUE TITLE
Question: general questions about ngBoilerplate

### ISSUE THREAD

**Issue by micfok** [ngbp/ngbp#221]
Hi Josh (and who else might be answering questions)! 

I'm mostly a backend dev (rails) so all this front-end stuff is very new to me (still getting the hang of Bower and Grunt...). Needless to say this was a big help and I love all the README's you've placed in the project. Really helps someone who's trying to wrap their head around the file structure, build & dev processes. 

Question #1: ngBoilerplate is explicitly NOT a server right? It doesn't have a node server, and a dev is supposed to serve the compiled bin files to an ftp server where they'll all work automagically? (This is compared to projects like angular-seed and angular-app, where they require you to run a node server to access to page.) 

Question #1.5: If that's the case, could a dev still use ngRoute? I was under the impression ngRoute is now a separate module that you have to import into the app now, and that it requires a server. 

Question #2: Why does ngBoilerplate use Angular 1.0.8 when 1.2 is out? I understand you probably built this when 1.0.8 was out, but I was wondering whether or not there were significant hurdles between those two versions and whether or not I would have problems upgrading later / relearn a number of features they changed.

**Comment by PaulL1** [comment]
Michael,

I also came to ngbp and angular from Rails (although it would be a stretch to describe me as a Rails dev).  I wrote a tutorial about that - you can find the rails 4 version here: http://technpol.wordpress.com/2013/11/09/angularjs-and-rails-4-crud-application-using-ng-boilerplate-and-twitter-bootstrap-3-tutorial-index/ and the rails 3 version here: http://technpol.wordpress.com/category/technology-2/tutorials/rails-3-and-angular/.  The rails 3 version is more complete, but the trails 4 one is better - I structured some of the code and UI better.  Those may give some help.

On that tutorial I upgraded to angular 1.2, and it didn’t really give any grief.

Note that the new version of ngbp is close, my current view is that it won’t be a huge change for developers, but it’s worth knowing that it’s a big upgrade.

Paul

**Comment by PaulL1** [comment]
Michael, noticed I didn't directly answer your questions.  Answers as I see them:
1 You still need a server.  In my case I'm using rails as the server with all the angular code just living in the public or assets directory, but either way angular gets served over http as a javascript file, rather than being ftp'd.  Although I suspect there is probably a way to make it work over ftp if that's what you really wanted.  :-)

1.5 You can still use ngRoute

2 Ngbp isn't really tied to the angular version at all - it's more about the build time scripts and the directory layout.  If you upgrade angularjs then you have to deal with all the dependencies that go with that, but it really isn't all that hard.  It's definitely coming to ngbp, but the larger upgrade is sucking a bit of the oxygen from smaller updates.

**Comment by micfok** [comment]
Hi Paul, 

Just skimmed through those tutorials. It looks like they'll be a lot of help going forward. Thank you very much!
