### ISSUE TITLE
common 3rd party libraries issue

### ISSUE THREAD

**Issue by maldworth** [ngbp/ngbp#224]
I checked bower, and I couldn't find if this 3rd party vendor file exists. So I figure I'd add it manually to my projects common directory (https://github.com/ngbp/ngbp/blob/v0.3.1-release/src/common/README.md)

But my problem is that the scripts.ForEach(...) will put my "src/common/mylib.js" at the bottom, below all of the angular module files that need to use it. So I found myself manually adding it to appear above, which is not a clean way to do this, because it now appears twice in my generated html file, once before all scripts, then again at the bottom. How have people dealt with this?

**Comment by joshdmiller** [comment]
Good question. The `src/common` directory shouldn't be used for vendor code precisely because of this problem. While it's not perfectly clean, create a folder inside `vendor` manually and put your file in there (being sure to manually add that file with git) and then add it to the `vendor.js` array as you normally would and it will be included in the right order.

Let me know if it doesn't work.

**Comment by maldworth** [comment]
Thanks, worked like a charm!
