### ISSUE TITLE
karma continuous crash when I add a vendor library

### ISSUE THREAD

**Issue by gostbuster** [ngbp/ngbp#319]
Hi guys,

I'm trying to get familiar with angular, grunt, bower, etc... and there might be something that I didn't understand.

I try to add a vendor library (angular-google-maps) in my project. In order to do that I did 

bower install angular-google-maps --save

this command install the library in vendor directory and update the bower.json adding a line in dependencies section.

When then I run grunt watch,

when I add the angular-google-maps dependency ( angular.module(['google-maps']),

the karma:continuous task crashes 

```
Firefox 32.0.0 (Mac OS X 10.9) AppCtrl isCurrentUrl should pass a dummy test FAILED
        minErr/<@/Users/jeremy/Projets/ng-boilerplate/vendor/angular/angular.js:78:5
```

And the angular-google-maps library is not copied in the build directory.

I also noticied that the build.config.js file is not updated and a line in section vendor_files (js) has not been added for angular-google-maps.

Is that file supposed to be edited manually every time a library is added ? I'm convinced that it shouldn't be like that.

Well, I'm sure that I'm missing or misunderstanding something but I don't know what.

Thanks in advance for your suggestions.

**Comment by BasitAli** [comment]
build.config.js needs to be manually updated to reference any css or js files you need your application to use. The reason, I guess, is because many vendor libraries come with multiple js/css files and you need to specify just the ones you need to use.

**Comment by gostbuster** [comment]
Hi @basitali and thanks for your answer.
Hum ok, I thought build.config.js was updated automatically when installing new libraries.

It is not explained in the documentation in "detailed install" section, but it seem's to be explained earlier in the page 

```
vendor/ - third-party libraries. Bower will install packages here. 
Anything added to this directory will need to be manually added to 
build.config.js and karma/karma-unit.js to be picked up by the build system.
```

then I guess I need to keep in mind that I have to edit the build.config.js whenever I wanna add a new vendor library.

Thanks

**Comment by joshdmiller** [comment]
@gostbuster Bower libraries are not consistent in how they are packaged, making it difficult to determine purely via automation which files to include.

Bower does provide a way for developers to specify which files to include through a `main` property in `bower.json`, but it's not used as often as it should be. We _could_ try to include those automatically, but that would require further discussion, particularly for the edge cases. In addition, many Bower packages include multiple optional components, further challenging the process. This is something that would be considered for [Warlock](http://getwarlock.com), though.

But in most apps, adding a third-party library is not a common occurrence. Early in development, we'll add one here and there, but it shouldn't be an ongoing challenge.

**Comment by garralab** [comment]
Hi, I know this is closed but I would like to add on this, because it's been repeatedly quite a pain in the last few months. More to add a point of view then to get a fix, especially thinking about Warlock, because I think it's the only thing unfriendly and unproductive of ngbp...

In my team often someone add various bower libraries just to test them and choose the one that adapts better to us. They obviously always have to modify the build.config.js but many times they forgot to use --save-dev when installing with bower. The result is that everytime there's a merge because bower install didn't add the files there's someone that gets that 
`AppCtrl isCurrentUrl should pass a dummy test FAILED`
with no other indication about the missing module.

The first few times we lost a lot of time on this, now we know we just need to completely comment out app.spec.js so grunt build will build no matter what and then run the application and in the browser we get a very easy to read error specifying which module can't be found.

I don't know if it's a problem with angular-mocks or karma logging, but it's clearly a bad thing if the fastest way to debug it is to comment out our tests.
I tried to solve it with some different approaches, but to no avail at the moment. I'll try again in my spare time but my understanding of karma is not as good as it should.
My best bet would be to check if the files listed in build.config.js exists before running the test (since they are loaded singularly in karma conf)

```
files: [
      <% scripts.forEach( function ( file ) { %>'<%= file %>',
      <% }); %>
      'src/**/*.js',
      'src/**/*.coffee',
    ],
```

but I haven't been able to get even close to a solution...
