### ISSUE TITLE
vendor\placeholders is excluded via gitignore but required for build

### ISSUE THREAD

**Issue by yaronguez** [ngbp/ngbp#322]
Hi, thanks for the great boilerplate!  One problem we just discovered, the vendor folder is excluded via gitignore vendor\placeholders is present in the repo and required by the project.  I got this working following your instructions but then, after making the boilerplate my own, submitted to our own repo.  Because of the gitignore, the vendor\placeholder was not included in our repo.  When our other developers pulled this repo, they thus did not get vendor\placeholder which is included in the build process and thus causes build to fail.  Is there a way to include placeholders in the bower.json file to avoid this from happening in the future?

**Comment by Matt-Jensen** [comment]
Would love to see this as well!

**Comment by joshdmiller** [comment]
Just a note, this should not happen unless the placeholders are _removed_ at some point. Otherwise, they are already in the repository so the `gitignore` will have no effect.

That said, the reason (as listed in several other issues, e.g. #120 #198) is that someone submitted the placeholders repo to bower, which can't work as it's unbuilt. The process for unregistering a repo was manual and outside of my control, which is why it was included manually here. There is now a way to unregister the other repo myself, so I'll give this a try and see what I can do.

In the meantime, this is a duplicate so I'll close it. Please keep the conversation going.

**Comment by jamesbrink** [comment]
This one caught me off guard as well.
