### ISSUE TITLE
Problems with Grunt Populating the Main Index

### ISSUE THREAD

**Issue by Hollowbean** [ngbp/ngbp#33]
After following the walk through, I've run into an issue where I'm not seeing grunt complete the addresses in the index correctly. I believe these files should be address via the main.less, which is there... but it's not turning the variable value into a string for render.

Any help?

```
<link rel="stylesheet" type="text/css" href="assets/<%= grunt.config.get('pkg.name') %>.css"/>
```

**Comment by joshdmiller** [comment]
Sorry you're having issues. :-(

I'm not sure I'm clear on the problem. You're opening `dist/index.html` (that is, the built version), right? And the build process all works without error? Also, you ran `bower install` to get Bootstrap, right?

If so, what do you see in the `link` tag? Do you see the right name or do you see the code you printed above?

**Comment by Hollowbean** [comment]
There were no issues, I'd just not understood the dist index file was the correct index.html. I have a feeling understanding Grunt is going to be critical to the usefulness of your build. I'm totally down with the directory organization you've set up and the baked in styles and tools which I use anyways.

I guess it's a good time to learn Grunt ;)

**Comment by joshdmiller** [comment]
This is actually not a feature of Grunt. `ngBoilerplate` is specifically designed to place the constructed files in a folder called `dist`, which is accomplished through many carefully configured Grunt tasks. There is a note in the Detailed Installation section of the readme:

> The built files are placed in the `dist/` directory. Open the `dist/index.html` file in your browser.

However, I should probably make this more clear.

As for understanding Grunt, check out this [overview of the tools](https://github.com/joshdmiller/ng-boilerplate/blob/tools-readme/tools.md) (it's not on the master branch yet) and then try reading through the Gruntfile. It's heavily commented because I want it to be understandable.

Please feel free to post more issues or questions - I want to make the documentation as strong as I can.
