### ISSUE TITLE
Can't create directories in src/app alphabetically less than 'app'

### ISSUE THREAD

**Issue by arw180** [ngbp/ngbp#333]
In both `karma-unit.tpl.js` and `Gruntfile.js`, the JS source is obtained using globbing like `src/**/*.js`. This does not guarantee that `app.js` will come first in `index.html` or the karma file, which happens if you create a directory in `src/app/` that is alphabetically less than 'app' (as in `app.js`). This results in the infamous angularjs error: `Module abc is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`

My solution was to manually include `app.js` in both `karma-unit.tpl.js` and `Gruntfile.js` (in the index:build task) before the JS source code globbing occurs.

I'd submit a pull request, but it doesn't appear this project is being actively developed anymore. If nothing else, I hope this saves someone else the hours it cost me.

**Comment by joshdmiller** [comment]
A key principle in creating angular apps with this structure is that you
must follow the "1 module = 1 file" approach. When you do, the order of the
files is completely irrelevant because `ng-app` specifies the entry point,
which specifies its dependencies, which specify their dependencies, ad
infinitum. But because of angular's module system and dependency injection,
the order the files are included never mattered because each file stood
alone.

My assumption is that you split a module across files, which caused your
ordering problem, which ngbp doesn't support.

Or is it something else?

**Comment by arw180** [comment]
Ah, yes that's the problem. I am creating all of the modules used throughout the application in app.js and then referencing them in other files (e.g. `angular.module('myApp.someModule', []);` statements in `app.js`, and `angular.module( 'myApp.someModule').controller(...)` statements in other files. 

At some point I stumbled on this as a recommended way to structure applications, not realizing that it violates a key principle of ngbp. 

Thanks for the response (and for ngbp in general, it's been a huge help)!

**Comment by joshdmiller** [comment]
Sweet! If you makes you feel any better, this question crops up frequently in many forms (that's how I knew what the problem was) - so you're not alone! But, yeah - mixing module definitions makes the components not "drag-and-droppable" anymore, and that's one of the key features of how ngbp organizes code. Also, it introduces all kinds of management problems for automated build systems (as you discovered) and no one's really been able to explain why it's worth the trouble. Maybe some day.

Anyway, glad is solved!
