### ISSUE TITLE
Add E2E Tests

### ISSUE THREAD

**Issue by devmao** [ngbp/ngbp#39]
Sorry guys, I'm sure that it's not the right place for asking but I need to add some e2e tests and I don't know how is's the best way to do it in ngBoilerplate/Karma.

Thanks for your patience!

**Comment by joshdmiller** [comment]
@devmao Adding E2E tests to ngBoilerplate is something I've been meaning to do. Here are the high-level steps:
1. Create a new config file called `karma/karma-e2e.js`. It will be very similar to the unit test config with the exception that it will look for `*.scenario.js` files instead of `*.spec.js` files.
2. Add an E2E test step to the `karma` build process in `Gruntfile.js`. This will just point to the different config file.
3. Add some E2E watch tasks, if you prefer.
4. Add it to the `default` build task and, optionally, the `watch` task.

Under this scheme, any file in your `src` directory that ends in `.scenario.js` will be tested. It really should be this simple.

Hope this helps. I'll leave this open for further discussion; feel free to ask follow up questions here. I renamed the title to something more actionable.

PS: If you implement this, a PR would be awesome. :-)

**Comment by rolaveric** [comment]
One thing I'd like to discuss is how to organise ngMockE2E:$httpBackend definitions.
From what I can tell, we need the following:
1. Somewhere to hold the `$httpBackend.when()` definitions.
2. A way to include the above definitions only for E2E tests.
3. And a way to include the `ngMockE2E` module for E2E tests.

Here's my idea for an implementation:
1. Create a `*.e2e.js` file for each 'module' which contains a `module('ngBoilerplate.module').run(function ($httpBackend) { ... })` function that contains all the `$httpBackend.when()` handling.
2. Create a `concat` definition in `Gruntfile.js` that concatenates all the `*.e2e.js` files to 'e2e.js'.
3. Extend the `index` task to compile the 'index.html' template in 'E2E' mode, to destination 'e2e-index.html'.
4. Change `src/index.html` to, if in "E2E" mode:
- Append `.e2e` to the end of the `ng-app` attribute.
- Include `e2e.js`
- Include a script tag with `module('ngBoilerplate.e2e', ['ngBoilerplate', 'ngMockE2E']);`

That's a rough plan - I'll give it a try and see what I can improve.

**Comment by rolaveric** [comment]
I think I've got a good solution: [444c9c4](https://github.com/rolaveric/ng-boilerplate/commit/444c9c48c82e9ea171f838f7f0b7b7e519b33c3a)

The `*.e2e.js` files seem to work quite well.
The `e2e-index.html` feels a little weird, but it works, and I can't think of a better alternative.
The closest I can think of is, working off the dicussion for #35, if `e2e.js` is included in the default `dev` mode, but removed in the `build-production` task.

What do you think?

I also had to do a bit of black-magic with the karma configuration.  Because we don't have a web server running, there's nothing to proxy off of... EXCEPT the karma server itself.
It's possible to declare a pattern under `files` which is `served`, but not `included`:

```
{pattern: 'dist/**/*', watched: false, included: false, served: true}
```

Then, from the E2E scenarios, you can browse to `/base/dist/e2e-index.html`.

**Comment by joshdmiller** [comment]
@rolaveric It's been about a month, but I haven't had time to look into this. I will be implementing E2E tests within the next few weeks. How's your solution been working for you? I've implemented #35 and it wouldn't be hard to extend it like you mentioned.

**Comment by rolaveric** [comment]
@joshdmiller It's been working great - e2e tests work, and I have fixtures to work with during development.

**Comment by cavarzan** [comment]
@rolaveric did you know if your improvement will be merged to the master branch?

**Comment by rolaveric** [comment]
@cavarzan I don't know, but I've made a pull request with changes to make it work with the latest master: https://github.com/joshdmiller/ng-boilerplate/pull/67

**Comment by cavarzan** [comment]
Thank you very much! I'll watch this issue.

**Comment by joshdmiller** [comment]
@cavarzan and @rolaveric - I'll try to get this (or something like it) into the next release, which should be sometime next week.

**Comment by revolunet** [comment]
great news, can't wait thanks :)

**Comment by pentatonicfunk** [comment]
waiting for new release for support e2e testing

**Comment by joshdmiller** [comment]
Obviously the "sometime next week" part didn't really happen. :-( 

I'm going to try to get to it next week, but the more PRs the better, though. :-)

**Comment by fraserxu** [comment]
Waiting for new release for support e2e testing +1. 

I've read about [Full-Spectrum Testing with AngularJS and Karma](http://www.yearofmoo.com/2013/01/full-spectrum-testing-with-angularjs-and-karma.html#testing-controllers) by [yearofmoo](https://github.com/yearofmoo). But unfortunately it's base on angular-seed and I can't follow up as I'm still new to karma and using `ng-boilerplate` in my project. Wish someone could write something about it.

**Comment by aruizca** [comment]
+1

**Comment by revolunet** [comment]
i guess we have to wait for the release of the new e2e test engine, aka "protractor".

**Comment by aruizca** [comment]
AS far as I know it has already been released: https://github.com/angular/protractor

**Comment by aruizca** [comment]
Anyway I am trying to use Karma following @rolaveric push request #67 and the angular-seed project to see if I come up with something. But unlike these two, I will be using the grunt-devserver task to serve the app and perform the e2e tests. I will also be using the grunt-parallel task to run the watch task along side the devserver task. Cheers

**Comment by joshdmiller** [comment]
This has been superseded by #196, which will be put into the next release in a couple of weeks.
