### ISSUE TITLE
Build / Vendor confusion

### ISSUE THREAD

**Issue by scharris** [ngbp/ngbp#43]
The "Read More ..." next to "build /" lands at the Vendor documentation page, not that for Build.  Also, this "Vendor" documentation says that the vendor directory contains Angular version 1.1.2, but in fact the vendor/ directory contains Angular 1.0.7.  The build directory however does contain 1.1.2.  Is it supposed to be like this, having two different Angular versions included?

**Comment by joshdmiller** [comment]
Hey @scharris. Yikes! How confusing is that?

As part of the work toward v0.3 landing in the next couple of days, a lot of things got a major overhaul. There is now only a single version of Angular and the docs are updated accordingly, so this is fixed. :-) 

Since this is a pretty major change, for now it's sitting on the `v0.3wip` branch if you want to check it out.
