### ISSUE TITLE
Why aren't Angular & Angular UI sources minified

### ISSUE THREAD

**Issue by IanMayo** [ngbp/ngbp#53]
Hi there - love the framework, at last there's a sensible approach to modular construction.

When I use developer tools to see the download files libs.js is the largest. When I look at libs.js I can see it's a concatenation of files from the Vendor package.

Is the responsibility on me (the developer) to decide whether to include standard or minified versions of these libs, or should it be the responsibility of grunt to minify them anyway?

Cheers,
Ian

**Comment by tbranyen** [comment]
You should leave it to Grunt.  Manually including minified sources is considered back practice almost universally.

**Comment by IanMayo** [comment]
Cool, thanks Tim.  

But, the current Grunt build doesn't minify (uglify) the AngularJS sources - it includes them in a 'monster' 850Kb lib.js file.

Is there an alternate build command, or config parameter that will either minify AngularJS, or use the AngularJS.min.js that's in the vendor folder?

**Comment by joshdmiller** [comment]
@IanMayo You're right; they should be minified. That was a terrible oversight. In v0.3 that I pushed out the other day, all files are minified and instead of having your app file and the libs file, you get only one file. This is much more efficient.

I recommend upgrading to v0.3 as it adds a lot of enhancements; but since it's a manual process, you can add minification of `libs.js` in your current version fairly easily. Right now, the `uglify` section of your Gruntfile should look something like this:

``` js
uglify: {
  options: {
    banner: '<%= meta.banner %>'
  },
  dist: {
    files: {
      '<%= distdir %>/assets/<%= pkg.name %>.min.js': [ '<%= distdir %>/assets/<%= pkg.name %>.annotated.js' ]
    }
  }
},
```

The easiest thing to do would be to change the files array to this:

``` js
files: {
  '<%= distdir %>/assets/<%= pkg.name %>.min.js': [ 
    '<%= distdir %>/assets/libs.js', 
    '<%= distdir %>/assets/<%= pkg.name %>.annotated.js'
  ]
}
```

And since you're including the libs _and_ your source, you can delete this line from your `src/index.html`:

``` html
<script type="text/javascript" src="assets/libs.js"></script>
```

You could also add another target in `uglify` to just create a minified version of libs.js, but this seems like the better approach to me.

Again, I recommend you upgrade to v0.3, but it does take a big of work. See #1. I'm going to go ahead and close this issue as it's solved in the new version, but if you have trouble getting the above to work do let me know.

**Comment by IanMayo** [comment]
"@IanMayo You're right; they should be minified"

Oh wow, I've never felt so flattered ;-)  I only encountered Angular/Grunt/Bower last week, and only encountered client-side JS development the week before.

I'm proud (& more than a little surprised) to have moved your project forward, and best of luck for the future.
