### ISSUE TITLE
How to store the project in my own repo while maintaining the link to yours for updating

### ISSUE THREAD

**Issue by timkindberg** [ngbp/ngbp#54]
I'm not a git wizard by any means so maybe this is a weird question. But I'm having trouble figuring out how I would clone your repo and then save it into my own repo (https://github.com/timkindberg/animation-sink), where the initial commit is the one right after editing package.json and some of the other config files. 

How do I do that? 
Also then how to I maintain the link to your git repo for making updates in the future?

**Comment by joshdmiller** [comment]
@timkindberg This is actually fairly straightforward, but the details depend on what you want to do.

First, add this to your repo as a remote and fetch the branches. This doesn't change any files on your side; it merely downloads all the references to other branches from GitHub.

``` sh
$ git remote add ngboilerplate git://github.com/joshdmiller/ng-boilerplate.git
$ git fetch ngboilerplate
```

You now have access to ngBoilerplate from within your repo, now and in perpetuity. But what happens next depends on what you want to do. If you want to copy all files from ngBoilerplate into your current branch (overwriting any conflicting files) then you can just do this:

``` sh
$ git checkout ngboilerplate/master -- .
```

This will, in essence, copy all files from the master branch of ngBoilerplate into your current working tree and stage them for commit. It will not commit them automatically and it will not bring any of the git commit history.

If instead you want to _merge_ the upstream ngBoilerplate with your repo (but still skip the commit history), then you can do an ordinary merge but squash the commits:

``` sh
$ git merge --squash --no-commit ngobilerplate/master
```

The "squash" will skip all of the commit history so your merge will end up with _one_ commit rather than all of them and the "no-commit" just doesn't automatically commit your files. You'll then have to make sure everything's alright before doing the commit.

So now that you have three options (clone like in the readme, add it to your existing repo, or merge it into your existing repo), which one do you pick? When I start a brand new project, I do this:

``` sh
$ mkdir my-new-project
$ cd my-new-project
$ git init .
$ touch README.md
$ git add README.md
$ git commit -m "chore(*): Initial commit"
$ git remote add ngboilerplate git://github.com/joshdmiller/ng-boilerplate.git
$ git fetch ngboilerplate
$ git checkout ngboilerplate/master -- .
$ vim package.json
$ vim bower.json
```

And then I change whatever else I need to (usually nothing) before committing it:

``` sh
$ npm install
$ bower install
$ grunt # obviously ensure it builds :-)
$ git status
$ git add . # this adds ALL files that aren't in .gitignore so do this with caution
$ git commit -m "chore(build): Added ngBoilerplate v0.3"
```

And now my history has only two commits, but I have a completely functional (and customized) version of ngBoilerplate for my new project.

I am considering creating a simple command-line app that will do this for you for v0.4 but I'm not sure if I will yet as  everyone has her own style.

This was long, but I hope I answered your question.

**Comment by timkindberg** [comment]
WOW! Thanks I will be reading this in detail tonight!

**Comment by timkindberg** [comment]
I guess I see a couple issues with this, when I update the package.json and bower.json—or any of the dev config files really—won't they be overwritten when I pull updates from ngboilerplate in the future?

How would you go about that? I guess it updates would have to be done manually...
