### ISSUE TITLE
ng-boilerplate without less

### ISSUE THREAD

**Issue by dcesiel** [ngbp/ngbp#75]
What changes would I need to make to use ng-boilerplate without less?

**Comment by joshdmiller** [comment]
Only a few. In fact, in the next version of ngBoilerplate less will be optional. But actually, CSS files should be included already but are not due to a bug. See #57.

Right now, an easy solution is to place them all in assets and then add them manually to the index.html. But that's pretty lame. It also won't work with the watch.

So the better way is to define a CSS array in the build config just like that less array and then use that in a recess subtask to concatenate the files (and optionally lint and compress them); I would also add a subtask to the watch to recompile the CSS. Finally, the compiled CSS file should be added to the index.html. Something more sophisticated will be in the next version, however.

Let me know if you'd like more guidance.
