### ISSUE TITLE
I want to use small blocks with ng-boilerplate

### ISSUE THREAD

**Issue by bhattkrishna19** [ngbp/ngbp#82]
I want to include small blocks for content in my module page 
i.e. 
there is one html page for view i want to break it in small parts like title, content and put those small html parts seperately and include it in my main view file, I tried with ng-include but it didnt work please help.

**Comment by joshdmiller** [comment]
Sorry you're having trouble. Its hard to say from that limited description,
so I'll just have to venture a guess.

Did you end your partials in `.tpl.html`? Otherwise they will be ignored by
the build, but you can easily change this by adding the extension of your
choice to the build config.

Else, what does the console say on page load? Does the build give any
errors? Where are you placing the partials and what are they called?

**Comment by bhattkrishna19** [comment]
hi i gone through your issue #71 and i found the solution i was not giving correct path to ng-include, Is there any ohter best way for using partial template instead of ng-include.
