### ISSUE TITLE
testacular-unit.js firefox dependancy

### ISSUE THREAD

**Issue by gnesher** [ngbp/ngbp#9]
Hi,

_edit_
Testacular is currently hard wired to use FF, any way to auto detect available browsers?

**Comment by joshdmiller** [comment]
I don't think so, but I'll have to defer to the Testacular experts here.

For what it's worth, since I'm on Linux, browser names have to be lowercase, so the default string doesn't work well. When I'm working locally, I actually comment out the browser string, leaving an empty array, and then connect whichever browser I want to Testacular manually by going to http://localhost:9018/. The tab can just be left open and it will always be used instead, with no fuss.

**Comment by joshdmiller** [comment]
Also forgot to mention that we need a browser string for Travis CI to work.

**Comment by brenthale** [comment]
For the next person to come along...

To work around this simply edit the testacular/testacular-unit.js file.   At the bottom of the file is the following:

browsers = [
  'Firefox'
];

Change it to be

browsers = [
];

Then as you run the tests (for me that meant I was doing a 'grunt watch', once it starts up the server simply open http://localhost:9018/ in the browser of your choice and it should work.  I was on Windows.

**Comment by joshdmiller** [comment]
@brenthale - Thanks for being more explicit about the steps than I was. This solution should work across all platforms.

Does anyone know of an answer to @gnesher's question?

**Comment by joshdmiller** [comment]
I haven't seen anything that leads me to believe auto-detection of browsers is currently possible, so I'm going to close this issue. If someone comes up with a solution, I'd be happy to reopen it!
