### ISSUE TITLE
How do I launch node webserver

### ISSUE THREAD

**Issue by arvindtm** [ngbp/ngbp#97]
Total Total Noobie here.

I installed the boilerplate. My Karma is set up.
How do I run node web server from the command line ( >node whichfile.js ?)
Which port on my local host it will run on ?

I like to see the index.html in my browser.

Thanks

**Comment by chungwong** [comment]
I have the same problem,
grunt watch was running fine, karma was up and browser appeared.

Running "karma:continuous" (karma) task
WARN [config]: config.configure() is deprecated, please use config.set() instead.
INFO [karma]: Karma v0.9.6 server started at http://localhost:9018/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 28.0.1500 (Linux)]: Connected on socket id kPq8Hmd6sgiH1oamdUm3

however, the url in the browser is with prot 9019,
now i don't know where I can see the build/index.html

Anyone can help My First step?
thanks

**Comment by ElliotPsyIT** [comment]
@chungwong You're very close, and simply need to open the build/index.html file in your browser.  You could drag and drop the file from Finder if you're on a Mac.  Or, type in the file location using the file:// protocol --

file://localhost/path/to/build/index.html

The reference for this in the documentation is found in the README.md file under the section 'Detailed Installation', as below with my emphasis:

To ensure your setup works, launch grunt:
`$ grunt watch`
The built files are placed in the build/ directory by default. **Open the build/index.html file in your browser** and check it out!

**Comment by chungwong** [comment]
thanks, that means it is not using http protocol?
now I simply opened build/index.html, and it doesn't make sense to me.
1. I suppose to develop the files under src directory, but it is telling me to open build/index.html?
2. even in build/index.html, it is not doing auto refresh.

how does it work actually? with yeoman, I run the server, then change the source, the server auto refreshes the page for me. what is the workflow in ng-boilerplate?

**Comment by joshdmiller** [comment]
@fielstem Great answer; you're exactly right. :-)

@chungwong Here's a little further clarification. Out of the box, there is no web server because one isn't needed. If you'd like to run one, run whichever you choose (but that configuration is up to you). 

So here's how the build process works:
1. You keep all your code inside `src/`, where you develop against it
2. You use Grunt to manage the build; e.g. `watch` to watch for changes or `default` to just build the whole darn thing. These tasks compile, minify, concat, etc. The built files are stored in `build/` for a development-friendly build and in `bin/` for a deployment-ready build.
3. You preview your work from the `build/` directory.
4. When all done, `grunt compile` and push your `bin/` directory to your server.

(These individual tasks are all covered in more detail in the READMEs.)

So the workflow is almost the same as with Yeoman, except we don't need a webserver.

Does that help?

**Comment by chungwong** [comment]
Thanks Josh,
You solved my questions.
I was thinking angular app always need a webserver but you opened my eyes.
great work Josh!!

**Comment by joshdmiller** [comment]
Ordinarily, you're right that an Angular app would need a webserver because it relies on XHR operations to get templates and whatnot. ngBoilerplate is different because we use the `html2js` task to combine all the templates into JavaScript (into the `templateCache`, specifically) and then concatenate that with our script files; all our templates and partials are included up front, so there are no XHR requests and so we don't need a server. :-)

**Comment by jackvsworld** [comment]
@joshdmiller If you do choose to run a webserver, how does that work with the existing directory structure? Would you put the server code somewhere under the src/ directory?

**Comment by winnemucca** [comment]
I am curious about this part as well.  I have a json file that I want to make a get request on.  I kept it inside the source file.  inside of get I am calling http like so(http://).  However, the file shows up as red on the Networks tab in dev tools.  Is there a certain amount of the path that we should put in next to the  http request?

**Comment by joshdmiller** [comment]
The particulars here are based on your webserver of choice, and as such are outside the purview of ngbp. But the broad strokes are that you want to serve `build/` or `dist/` as static files, probably from the root of your webserver. E.g. you could add a `server.js` like this to the root of the project:

``` js
var express = require( 'express' );
var path = require( 'path' );
var app = express();

app.use( express.static( 'build' ) );

// catchall route
app.get( function ( req, res ) {
  res.sendfile( path.join( __dirname, 'build', 'index.html' ) );
});
```

Now anything that ends up in the `build/` directory is servable. Any JSON file you keep in `src/assets` will automatically be [picked up by the build](https://github.com/ngbp/ngbp/blob/v0.3.2-release/Gruntfile.js#L101). So a file like `src/assets/my-data.json` will be fetchable with `GET /assets/my-data.json`.

**Comment by winnemucca** [comment]
Simple enough.  Thank you
