### ISSUE TITLE
Support for Typescript

### ISSUE THREAD

**Issue by demetriusnunes** [ngbp/ngbp#99]
Please, add support for compiling Typescript files

**Comment by JanPrinsloo** [comment]
I'm using ngBoilerplate with typescript in visual studio with no hassles. Let visual studio generate the .js files. grunt is already configured to automatically pick up *.js files only, so you don't need to do anything special.

**Comment by joshdmiller** [comment]
@demetriusnunes I am aware of Typescript but am not at all familiar with it so this feature couldn't be developed by me. I also worry about having too many features out of the box with ngBoilerplate; it should be fairly easy to extend the build scripts individually to get something like this working - check out the CoffeeScript tasks for inspiration; they can probably mostly be copied.

All that said, if someone wants to submit a PR, I'd be happy to consider it; if it's relatively minimal, I have no problem including it. Semi-related, how popular is Typescript?

**Comment by FrankShaw** [comment]
+1 I think this would be a great place where people who want to use angular with typescript could come to find best practices, and examples of common angular+typescript patterns. That being said, I could take a crack at making a typescipt version of ngbp. 

Depending on how large the change is, it might be best to include a link to any different verisons of this project (coffeescript, typescript, etc...) in the readme rather than including them all in the base project.

**Comment by manbearwiz** [comment]
This seems like a definite use case for the [Warlock](https://github.com/ngbp/warlock) project. All that would need to be done is create a spell-typescript similar to the existing [spell-coffeescript](https://github.com/ngbp/spell-coffeescript). Read more about warlock [here](https://github.com/ngbp/warlock/wiki).

**Comment by joshdmiller** [comment]
Indeed, @kmb32123. In fact, there's an issue on the Trello board for a Typescript spell for Warlock.

As for ngbp, there are few problems with including TypeScript support. @FrankShaw touched on one, which is that it is awkward to have so much stuff in ngbp when most people won't use most of it. Another challenge would be keeping two repositories up to date with each other.

As such, ngbp's Grunt-based build system will _not_ be supporting Typescript. It was a similar mistake to include support for CoffeeScript. Warlock will soon replace ngbp's Grunt-based build script and Typescript would be great to include there.

Within the next week or so, I'm going to try to organize a Google Hangout for those interested in taking an early look at and/or contributing to Warlock. If you're interested, stay tuned.

For now, since this problem will not be solved in this repository, I'll go ahead and close this issue. Please feel free to continue the discussion, however. :smile:

**Comment by inongogo** [comment]
@FrankShaw @kmb32123 
You can check out my attempt to add TypeScript to the Yeoman generator-ngbp. It lacks testing for TypeScript (I havn't been able to make it work, thought about changing the tests to plain JavaScript). The Yeoman generator is called generator-icengbp and is available on NPM. It's possible to generate a modified version of ngBoilerplate with or without TypeScript and also to generate simple templates for controllers, services and directive. It's also available on https://github.com/ingo777/generator-icengbp
